import { Inter } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.css';
import 'font-awesome/css/font-awesome.min.css'
import './globals.css';
// import './bootstrap/dist/js/bootstrap.bundle.min.js';
import Header from "@/Components/layouts/Header";
import Footer from "@/Components/layouts/Footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body>
        <Header/>
        {children}
        <Footer/>
        </body>
      
    </html>
  )
}
